import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Arman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} >
        <h1 className={styles.title}>
          Hi, I&apos;m Arman.
        </h1>
        <div className={styles.grid}>
          <Link href="/aboutme" className={styles.card}>
            <h2 className={styles.card}>About me &rarr;</h2>
          </Link>

          <Link href="/contact" className={styles.card}>
            <h2 className={styles.card}>Contact &rarr;</h2>
          </Link>

          <Link href="/musings" className={styles.card}>
            <h2 className={styles.card}>Musings &rarr;</h2>
          </Link>
        </div>
      </main>
    </div>
  )
}
