import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Arman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} >
        <h1 className={styles.title}>
          Hi, I&apos;m Arman.
        </h1>

        <div className={styles.grid}>
          <link href="/aboutme" className={styles.card}>
            <h2>About me &rarr;</h2>

          </link>

          <link href="/contact" className={styles.card}>
            <h2>Contact &rarr;</h2>
          </link>

          <link
            href="/musings"
            className={styles.card}
          >
            <h2>Musings &rarr;</h2>
          </link>

        </div>
      </main>
    </div>
  )
}
